name: Publish to Rubygems

on:
  push:
    tags:
      - v*
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.2'

      - name: Build and push gem
        env:
          RUBYGEMS_API_KEY: "${{secrets.RUBYGEMS_API_KEY}}"
        run: |
          bundler install -j4
          gem build -o karist.gem
          gem push ./karist.gem --key $RUBYGEMS_API_KEY
